### ISSUE TITLE
`node status` fails with custom Eth1 providers

### ISSUE THREAD

**Issue by zah** [rocket-pool/smartnode-install#43]
I've tried to configure my RocketPool smart node with an external Eth1 provider, using the following config:

```yml
chains:
  eth1:
    client:
      selected: "custom"
      params:
      - env: INFURA_PROJECT_ID
        value: ""
      - env: ETHSTATS_LABEL
        value: ""
      - env: ETHSTATS_LOGIN
        value: ""
      - env: PROVIDER_URL
        value: "ws://10.4.0.165:8546"
  eth2:
    client:
      selected: nimbus
      params:
      - env: CUSTOM_GRAFFITI
        value: "Nimbus on RocketPool"
```

`ws://10.4.0.165:8546` is a Geth instance that I've verified to be accessible within the container by executing `docker exec -it <eth1-container-id> /bin/bash` and then connecting with `telnet`.

When I run a command such as `rocketpool node status`, I get the following error:

```
Could not get node status: invalid character 'E' looking for beginning of value
```

The same problem appears if I try to use a `http://...` URL or if I omit the protocol prefix altogether.

**Comment by moles1** [comment]
Thanks, we'll look at implementing a fix for this in an upcoming release.

FYI, RP uses a lightweight HTTP / WS proxy within a docker container to route requests to either Infura or custom eth1 providers. For Infura, this will automatically set the protocol based on the type of connection required.

It looks like you're experiencing this issue because this doesn't happen for custom providers at the moment, which will need to be addressed. If you're using Nimbus it will only communicate with your eth1 client over ws, while the smartnode binaries use http, so both are required in your case.

The proxy is only a convenience to streamline configuration, so in the meantime you can bypass it and connect to your eth1 client directly if you like. Just modify the following lines under `~/.rocketpool/config.yml`:
```
chains:
  eth1:
    provider: http://10.4.0.165:8545
    wsProvider: ws://10.4.0.165:8546
```
