### ISSUE TITLE
[Feature Request] Option to open up metrics ports on docker

### ISSUE THREAD

**Issue by sam-semillia** [rocket-pool/smartnode-install#67]
Hi,

I am running Prometheus and Grafana on an external device. Therefore, after upgrading the smartnode stack I need to open the metrics ports each time by hand for

- eth2
- node
- validator
- watchtower

It would be great, if the installer does not only ask for the port of the respective metrics, but also if the respoective metrics port should be exposed in docker, making it available in the network.

Thanks, BR

**Comment by benv666** [comment]
So I had the same situation, before v1.3.0 I manually tinkered with the `docker-compose.yml` to enable the metrics and map these ports. Today I switched to v1.3.0 and did the same thing using the new override mechanic.
What made me happy was disabling the metrics in the `rocketpool service config` `Monitoring / Metrics` part, so it doesn't start prometheus etc. 
Then making override snippets in the `override` folder to allow my prometheus to reach them.
For example this is my `override/validator.yml`:
```
version: "3.7"
services:
  validator:
    x-rp-comment: Add your customizations below this line
    environment:
      ENABLE_METRICS: "true"
    ports:
      - "127.0.0.1:9101:9101"
```
or my `override/node.yml`:
```
version: "3.7"
services:
  node:
    x-rp-comment: Add your customizations below this line
    environment:
      - ENABLE_METRICS=true
    ports:
      - "127.0.0.1:9102:9102"
```

Hope this helps!
